name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          curl -L https://mirror.pilotfiber.com/ubuntu-iso/noble/ubuntu-24.04.1-desktop-amd64.iso > debian.iso
          sha256sum ./*.iso
          sudo mount debian.iso /mnt
          sudo tree /mnt
          cat /mnt/boot/grub/grub.cfg
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu
          path: ${{ github.workspace }}/*.iso
