name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          brew install dpkg
          ls /usr/local/bin
          ls /usr/bin
          python -m pip install --upgrade pip
          pip install pyinstaller
          wget https://wiki.t2linux.org/tools/firmware.sh
          mv firmware.sh main.py
          pyinstaller --onefile --clean main.py
          chmod a+x ./dist/main
          mv ./dist/main ./
          ./main /usr/share/firmware firmware.tar
          tar xvf firmware.tar
          base64 main > fw.txt
          cd brcm
          ls

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/fw.txt
