name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          curl -L http://mirror.keystealth.org/debian-cd/12.8.0-live/amd64/iso-hybrid/debian-live-12.8.0-amd64-gnome.iso > debian.iso
          sha256sum ./*.iso
          sudo mount debian.iso /mnt
          sudo tree /mnt
          echo "GRUB STARTS HERE"
          cat /mnt/boot/grub/grub.cfg
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu
          path: ${{ github.workspace }}/*.iso
