name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-12
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget https://www74.zippyshare.com/d/YTrt8hvZ/17067/Tuxera.NTFS.2021.1.dmg
          hdiutil attach $(pwd)/Tuxera.NTFS.2021.1.dmg
          ls /Volumes

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2
          path: /Library/Application\ Support/Paragon\ Software/uc.extfs
