name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          df -h
          echo dotnet
          echo
          sudo rm -rvf /usr/local/share/dotnet
          df -h
          echo android
          echo
          sudo rm -rvf /usr/local/lib/android
          df -h
          echo ghc
          echo
          sudo rm -rvf /opt/ghc
          sudo rm -rvf /usr/local/.ghcup
          df -h
          echo codeql
          echo
          sudo rm -rvf /opt/hostedtoolcache/CodeQL
          df -h
          echo cache
          echo
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          #path: /boot/config-6.7.6-x64v4-xanmod1h
          path: ${{ github.workspace }}/sketchy.tar.gz
