name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          curl -s --compressed "https://adityagarg8.github.io/t2-ubuntu-repo/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg >/dev/null
          sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
          sudo apt update
          sudo apt install t2-kernel-script
          update_t2_kernel
          
          wget https://github.com/t2linux/T2-Ubuntu-Kernel/releases/download/v6.1-2/linux-headers-6.1.0-t2-jammy_6.1.0-2_amd64.deb
          wget https://github.com/t2linux/T2-Ubuntu-Kernel/releases/download/v6.1-2/linux-image-6.1.0-t2-jammy_6.1.0-2_amd64.deb
          sudo apt install ./*.deb
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/linux/*.patch
