name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          git clone --depth 1 https://github.com/torvalds/linux.git
          git clone -b devel/6.8 https://github.com/t2linux/linux-t2-patches.git
          cd linux
          git config --global user.name "Aditya Garg"
          git config --global user.email "gargaditya08@live.com"
          cp ../linux-t2-patches/1001* ./
          cp ../linux-t2-patches/900* ./
          git apply ./*.patch
          git add .
          git commit -m "Add apple-bce driver"
          git format-patch -1 HEAD

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          #path: /boot/config-6.7.6-x64v4-xanmod1
          path: ${{ github.workspace }}/linux/*.patch
