name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          wget https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/debian-12.5.0-amd64-DVD-1.iso
          sudo mount debian-12.5.0-amd64-DVD-1.iso /mnt
          tree /mnt
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          #path: /boot/config-6.7.6-x64v4-xanmod1h
          path: ${{ github.workspace }}/firmware
