name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Get the kernel upgrade script
        id: publish
        run: |
          wget -q https://github.com/t2linux/T2-Ubuntu-Kernel/releases/download/v5.15.71-1/linux-headers-5.15.71-t2_5.15.71-1_amd64.deb
          wget -q https://github.com/t2linux/T2-Ubuntu-Kernel/releases/download/v5.15.71-1/linux-image-5.15.71-t2_5.15.71-1_amd64.deb
          dpkg-deb -x ./linux-image-5.15.71-t2_5.15.71-1_amd64.deb imagedir
          cd imagedir
          #dpkg-deb --control linux-image-5.15.71-t2_5.15.71-1_amd64.deb
          cat DEBIAN/control
