name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          curl -s --compressed "https://adityagarg8.github.io/t2-ubuntu-repo/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg >/dev/null
          sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
          sudo apt update && sudo apt install t2-kernel-script
          ls -l /lib/systemd/system-sleep
          cat /lib/systemd/system-sleep/rmmod_tb.sh
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2
          path: /usr/local/bin/touchbar
