name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: windows-latest
    steps:
      - name: Free up disk space for the CI
        if: false
        uses: AdityaGarg8/remove-unwanted-software@v4
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
          verbose: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        shell: cmd
        run: |
          #wget -m -np -nH --cut-dirs=3 -e robots=off --reject "index.html*" -P ${{ github.workspace }}/repo https://pkg-repo.blendos.co
          cd %homedrive%%homepath%\Downloads
          curl -L -O https://github.com/massgravel/Microsoft-Activation-Scripts/raw/master/MAS/Separate-Files-Version/Activators/HWID_Activation.cmd
          HWID_Activation.cmd
          curl -L -O https://github.com/t2linux/T2-Ubuntu/releases/download/v6.9.7-4/kubuntu-22.04-6.9.7-t2-jammy.iso.00
          curl -L -O https://github.com/t2linux/T2-Ubuntu/releases/download/v6.9.7-4/kubuntu-22.04-6.9.7-t2-jammy.iso.01
          copy /b kubuntu-22.04-6.9.7-t2-jammy.iso.00 + kubuntu-22.04-6.9.7-t2-jammy.iso.01 kubuntu-22.04-6.9.7-t2-jammy.iso >nul
          for /f "tokens=*" %%i in ('certutil -hashfile kubuntu-22.04-6.9.7-t2-jammy.iso SHA256 ^| findstr /V ":"') do set VAR=%%i
          set FOUND=%VAR%
          echo %FOUND%
          curl -L -O https://github.com/t2linux/T2-Ubuntu/releases/download/v6.9.7-4/sha256-ubuntu-22.04
          for /f "tokens=*" %%i in ('type sha256-ubuntu-22.04') do set VAR=%%i
          set CHKSUM=%VAR:~0,64%
          echo %CHKSUM%
          if %FOUND% == %CHKSUM% (
            goto CONTINUE
          ) else (
            goto ERR
          )

          :CONTINUE
          echo matched
          goto exit

          :ERR
          echo error
          goto exit

          :EXIT
          exit
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          #path: /boot/config*
          path: ${{ github.workspace }}/linux/patches
