name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          git clone -b test https://github.com/lemmyg/t2-kubuntu.git
          curl -O https://cdimage.ubuntu.com/kubuntu/releases/24.10/release/kubuntu-24.10-desktop-amd64.iso
          sed -i "s/ISO_IMAGE=\/home\/lemmyg\/Downloads\/kubuntu-24.10-desktop-amd64.iso/ISO_IMAGE=${{ github.workspace }}\/kubuntu-24.10-desktop-amd64.iso/g" ./t2-kubuntu/build_in_docker.sh
          cd t2-kubuntu
          sudo chmod a+x ./build_in_docker.sh
          sudo ./build_in_docker.sh
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kubuntu
          path: /root/work/output/*.iso
