name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          sudo apt update
          sudo apt install tree wget -y
          wget https://github.com/t2linux/T2-Ubuntu/releases/download/v6.3.1-1/kubuntu-23.04-6.3.1-t2-lunar.z01
          wget https://github.com/t2linux/T2-Ubuntu/releases/download/v6.3.1-1/kubuntu-23.04-6.3.1-t2-lunar.zip
          cat kubuntu-23.04-6.3.1-t2-lunar.z?? > kubuntu-23.04-6.3.1-t2-lunar.zip
          unzip kubuntu-23.04-6.3.1-t2-lunar.zip
          tree ./kubuntu-23.04-6.3.1-t2-lunar
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/linux-stable/*.patch
