name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget https://cloudflare-ipfs.com/ipfs/bafykbzacecybfe3tmttd5oskhlggcsnifdcboakv2um7upewvt6phi5wazsz2?filename=K.%20Park%20-%20Park%27s%20Textbook%20of%20Preventive%20and%20Social%20Medicine-Banarsidas%20Bhanot%20Publishers%20%282023%29.pdf

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/*.pdf
