name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v4
        if: false
        with:
         remove-android: 'true'
         remove-dotnet: 'true'
         remove-haskell: 'true'
         remove-codeql: 'true'
         remove-docker-images: 'true'
         remove-large-packages: 'true'
         remove-cached-tools: 'true'
         remove-swapfile: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          sudo apt update
          sudo apt install transmission-cli transmission-daemon tree
          curl -L https://gist.github.com/AdityaGarg8/dc4458bb052d4f49e257623ea338ff96/raw/f468069d817c96afb62ebc2e337d8fd2bd519c96/Liberty%2520City%2520Preservation%2520Project%2520-%2520FiveM.zip.torrent > cyberpunk.torrent
          aria2c --show-files cyberpunk.torrent
          transmission-daemon -gsr 0
          transmission-cli cyberpunk.torrent
          #rm *.aria2
          tree
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Liberty City Preservation Project - FiveM'
          path: ${{ github.workspace }}/*.zip
