name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          git clone -b bits/ibridge https://github.com/kekrby/linux-t2.git
          cd linux
          git format-patch -12 HEAD
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2
          path: ${{ github.workspace }}/linux/*.patch
