name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-13
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget https://github.com/AdityaGarg8/ESET-KeyGen/releases/download/v4/ESET-KeyGen_v4_macos
          chmod a+x ESET-KeyGen_v4_macos
          #wget https://www.python.org/ftp/python/3.13.1/python-3.13.1-macos11.pkg
          #sudo installer -pkg ./python-3.13.1-macos11.pkg -target /
          #python -V
          ./ESET-KeyGen_v4_macos --chrome --key --skip-update-check --no-logo --disable-progress-bar
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kubuntu
          path: ${{ github.workspace }}/*.iso
