name: Generate md5 sums
on: [push]
jobs:
  Generate-Sums:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo
      run: |
         git clone https://github.com/AdityaGarg8/Apple-WiFi-Firmware.git
         sed -i 's/Wi-Fi/Wifi/g' ${{ github.workspace }}/Apple-WiFi-Firmware/README.md
    - name: Push the change
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'Apple-WiFi-Firmware'
        destination-github-username: 'AdityaGarg8'
        destination-repository-name: 'Apple-WiFi-Firmware'
        #user-email: gargaditya08@live.com
       # user-name: Aditya Garg
        target-branch: 16,1
        
