name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          git clone --depth 10 https://github.com/AdityaGarg8/linux.git
          cd linux/fs/hfsplus
          grep -R label . || echo "error 1"
          echo
          grep -R LABEL . || echo "error 2"
          echo
          grep -R Label . || echo "error 3"
          git format-patch -1 HEAD
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/linux/*.patch
