name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Get the kernel upgrade script
        id: publish
        run: |
         official=$(uname -r | grep azure || true)
         if [[ $official = "" ]]
         then
         echo "t2"
         else
         echo "off"
         fi
