name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: macos-13
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          MAIL=developermail
          wget -q https://github.com/AdityaGarg8/ESET-KeyGen/releases/download/vtestfinal/ESET-KeyGen_vtestfinal_macos_amd64
          chmod a+x ESET-KeyGen_vtestfinal_macos_amd64
          echo "==> Testing amd64"
          echo
          ./ESET-KeyGen_vtestfinal_macos_amd64 --chrome --key --email-api ${MAIL} --skip-webdriver-menu --skip-update-check || true
          echo
          wget -q https://github.com/AdityaGarg8/ESET-KeyGen/releases/download/vtestfinal/ESET-KeyGen_vtestfinal_macos_arm64
          echo "== Testing arm64"
          echo
          ./ESET-KeyGen_vtestfinal_macos_arm64 --chrome --key --email-api ${MAIL} --skip-webdriver-menu --skip-update-check || true
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          #path: /boot/config-6.7.6-x64v4-xanmod1h
          path: ${{ github.workspace }}/built-iso.zip
