name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-11
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Get the kernel upgrade script
        id: publish
        run: |
          find / -name "*.ptb"
        #  system_profiler SPHardwareDataType | grep "Model Identifier"
        #  bash ./firmware.sh
          
