name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Get the kernel upgrade script
        id: publish
        run: |
          sudo curl -o /usr/bin/update_t2_kernel "https://raw.githubusercontent.com/t2linux/T2-Ubuntu-Kernel/script/debian.sh"
          sudo chmod 755 /usr/bin/update_t2_kernel
          update_t2_kernel
