name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-14
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          brew install dpkg
          wget https://wiki.t2linux.org/tools/firmware.sh
          python3 firmware.sh /usr/share/firmware ${{ github.workspace }}/firmware.tar
          tar -xf ${{ github.workspace }}/firmware.tar
          cd ${{ github.workspace }}
          mkdir deb
          cd deb
          mkdir DEBIAN
          mkdir usr
          cd usr
          mkdir lib
          cd lib
          mkdir firmware
          cd ..
          cd ..
          cd DEBIAN
          echo "Package: apple-firmware" > control
          echo "Version: 14.4.1" >> control
          echo "Maintainer: Aditya Garg" >> control
          echo "Architecture: amd64" >> control
          echo "Description: Wi-Fi and Bluetooth firmware for T2 and Apple Silicon Macs" >> control
          sudo chmod a+x ./control
          cd ..
          cp -r ${{ github.workspace }}/brcm ${{ github.workspace }}/deb/usr/lib/firmware
          dpkg-deb --build --root-owner-group -Zgzip deb
          dpkg-name ./deb.deb
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          #path: /boot/config-6.7.6-x64v4-xanmod1h
          path: ${{ github.workspace }}/linux/0001*.patch
