name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-12
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          brew install --cask paragon-extfs
          ls -a /Library/Application\ Support/Paragon\ Software/uc.extfs

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2
          path: /Library/Application\ Support/Paragon\ Software/uc.extfs
