name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          REPO=https://github.com/kekrby/tiny-dfr.git
          COMMIT_HASH=85c565a0eb6572249db8ffa46e37be7ac9fc400a
          VERSION=0.2.0-2
          curl -s --compressed "https://adityagarg8.github.io/t2-ubuntu-repo/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg >/dev/null
          sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
          sudo apt update -y
          #sudo apt upgrade -y
          sudo apt-get install -y gir1.2-coglpango-1.0 gir1.2-pango-1.0 libcogl-pango-dev libghc-gi-pango-dev \
          libghc-pango-dev libghc-yi-frontend-pango-dev libpango1.0-dev libudev-dev libinput-dev
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone -b wip/t1-support ${REPO}
          cd tiny-dfr
          git checkout ${COMMIT_HASH}
          wget https://raw.githubusercontent.com/AdityaGarg8/t2-ubuntu-repo/main/.github/patches/0002-Use-older-version-of-cairo.patch
          git am ./*.patch
          cargo b --release
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/tiny-dfr/target/release/tiny-dfr
