name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          ioreg -l | grep RequestedFiles | cut -d "/" -f 5 | rev | cut -c 4- | rev
          ioreg -l | grep RequestedFiles | cut -d "/" -f 3 | cut -d "\"" -f 1
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/firmware.tar.gz
