name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          cd /usr/bin
          sudo wget https://raw.githubusercontent.com/t2linux/T2-Ubuntu-Kernel/script/t2-kernel-script/usr/bin/update_t2_kernel
          sudo chmod a=rwx /usr/bin/update_t2_kernel
          update_t2_kernel
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/linux/*.patch
