name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-12
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          sudo systemsetup -setusingnetworktime off
          sudo date 1025134522
          brew install --cask tuxera-ntfs
          sudo shutdown -r now
          ls -a "/Library/Application Support/Tuxera NTFS"

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2
          path: "/Library/Application Support/Tuxera NTFS/.activation"
