name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        if: false
        uses: AdityaGarg8/remove-unwanted-software@v4
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
          verbose: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          curl -L https://nightly.link/AdityaGarg8/random/actions/runs/12863073686/Liberty%20City%20Preservation%20Project%20-%20Singleplayer.zip > horizon.zip
          unzip -d horizon horizon.zip
          tree
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          #path: /boot/config*
          path: ${{ github.workspace }}/linux/patches
