name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          KERNEL_VERSION=6.1.30
          KERNEL_REPOSITORY=https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
          git clone --depth 1 --single-branch --branch "v${KERNEL_VERSION}" \
          "${KERNEL_REPOSITORY}"
          cd linux-stable
          git config --global user.name "No name"
          git config --global user.email "noname@example.com"
          git revert --no-edit f8a6c53ff1d91acd5a20eb627edbffd816eb9a4e
          git revert --no-edit c35105f375b530bc27e03ea9250b1c26dd4cae86
          git format-patch -2 HEAD
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/linux-stable/*.patch
