name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v4
        with:
         remove-android: 'true'
         remove-dotnet: 'true'
         remove-haskell: 'true'
         remove-codeql: 'true'
         remove-docker-images: 'true'
         remove-large-packages: 'true'
         remove-cached-tools: 'true'
         remove-swapfile: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          sudo apt update
          sudo apt install aria2 tree
          curl -L https://gist.github.com/AdityaGarg8/f23212553277faf2e860f79848bcb0b4/raw/ed81d08244e881a6faec6d9a1cda128964d95402/Cyberpunk%25202077%2520%255BFitGirl%2520Repack%255D.torrent > cyberpunk.torrent
          aria2c --show-files cyberpunk.torrent
          aria2c --select-file=2 --seed-time=0 cyberpunk.torrent
          rm *.aria2
          tree
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu
          path: ${{ github.workspace }}/Cyberpunk*/*
