name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-14
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          brew install dpkg
          wget https://wiki.t2linux.org/tools/firmware.sh
          python3 firmware.sh /usr/share/firmware ${{ github.workspace }}/firmware.tar
          tar -xfC ${{ github.workspace }}/brcm firmware.tar
          cd brcm
          ls
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          #path: /boot/config-6.7.6-x64v4-xanmod1h
          path: ${{ github.workspace }}/linux/0001*.patch
