name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          DOCKER_IMAGE=ubuntu:22.10
          docker pull ${DOCKER_IMAGE}
          docker run \
          -t \
          -v "$(pwd)":/repo \
          ${DOCKER_IMAGE} \
          /bin/bash -c "cd /repo && \
          apt-get update && \
          apt-get install -y lsb-release git wget && \
          mkdir /tmp/artifacts && \
          git clone https://github.com/t2linux/T2-Ubuntu-Kernel.git && \
          sed -i "s/CODENAME=.*/CODENAME=external/g" /repo/T2-Ubuntu-Kernel/build.sh && cd /repo/T2-Ubuntu-Kernel && \
          cat /repo/T2-Ubuntu-Kernel/build.sh"
