name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          sudo apt update
          sudo apt install python3-pip
          sudo pip install -r requirements.txt
          sudo python3 main.py --account --force
          sudo python3 main.py --account --force
          sudo python3 main.py --force
          echo "Account:" >> $GITHUB_STEP_SUMMARY
          cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
          cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/linux-t2/*.patch
