name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          cat << EOF > entrypoint.sh
          cd /build
          useradd builduser -m
          passwd -d builduser
          pacman -Syu --noconfirm --needed sudo base-devel
          printf 'builduser ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
          chown -R builduser:builduser ./
          sudo -u builduser gpg --keyserver keyserver.ubuntu.com --recv-keys 38DBBDC86092693E
          uname -r
          EOF

          docker run -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/linux-stable/*.patch
