name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          git config --global user.name "Test test"
          git config --global user.email "exasa@example.com"
          git clone --depth 1 https://github.com/torvalds/linux
          git clone https://github.com/t2linux/linux-t2-patches.git
          cd linux
          cp ../linux-t2-patches 100* ./
          git am 1001*
          git am 1002*
          patch -Np1 < 1003-add-modalias-to-apple-bce.patch
          git add .
          git commit -m "add modalias to apple-bce"
          git format-patch -1 HEAD

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: linux/0001*
