name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Get the kernel upgrade script
        id: publish
        run: |
          curl -fSL https://download1320.mediafire.com/htnscr1drjhg/2puw5hkdasm9f7d/Linux+File+Systems+for+Windows+by+Paragon+Software.exe > "%Linux File Systems for Windows by Paragon Software.exe"
          curl -fSL https://download1508.mediafire.com/ordy9msat54g/s7uamadvgym43uj/paragon_service.exe > "paragon_service.exe"
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: ${{ github.workspace }}/*.exe
