name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          git clone https://github.com/t2linux/linux-t2-patches.git
          mkdir patches
          cp ./linux-t2-patches/*patch ./patches
          cd patches
          ls > ../linux-t2-patches/list.conf
          echo
          cat ../linux-t2-patches/list.conf
          sed -i -e 's/^/patches\//' ../linux-t2-patches/list.conf
          echo
          cat ../linux-t2-patches/list.conf
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/linux/*.patch
