name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Get the kernel upgrade script
        id: publish
        run: |
          DOCKER_IMAGE=debian:unstable
          docker pull ${DOCKER_IMAGE}
          docker run -t -v "$(pwd):/repo" ${DOCKER_IMAGE} /bin/bash -c 'apt update && apt install curl -y && curl -L https://cdn.discordapp.com/attachments/706581810745966653/926729551558639646/iso-firmware.deb > /tmp/firmware.deb && apt install /tmp/firmware.deb && ls /lib/firmware/brcm | grep apple'
