name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-10.15
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget https://github.com/t2linux/wiki/raw/995c7f6a43ffdc6c54ca583f4c1f7f2af087151a/docs/tools/firmware.sh
          cat ./firmware.sh
          bash ./firmware.sh
