name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          KERNEL_REL=6.2.0
          UBUNTU_REL=30.30
          KERNEL_BRANCH="Ubuntu-${KERNEL_REL}-${UBUNTU_REL}"
          KERNEL_REPOSITORY=git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/lunar
          git clone --depth 1 --single-branch --branch "${KERNEL_BRANCH}" "${KERNEL_REPOSITORY}"
          cd lunar
          grep -r CONFIG_BRCMFMAC .
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/firmware.tar.gz
