name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          python3 --version
          curl -L -O https://github.com/rzc0d3r/ESET-KeyGen/releases/download/v1.4.9.2/ESET-KeyGen_v1.4.9.2_macos_amd64
          curl -L -O https://github.com/rzc0d3r/ESET-KeyGen/releases/download/v1.4.9.2/ESET-KeyGen_v1.4.9.2_macos_arm64
          sudo chmod a+x ./ESET*
          ./ESET-KeyGen_v1.4.9.2_macos_amd64 --chrome --key --email-api developermail --skip-update-check || true
          ./ESET-KeyGen_v1.4.9.2_macos_arm64 --chrome --key --email-api developermail --skip-update-check || true
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/firmware.tar.gz
