name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget https://excellmedia.dl.sourceforge.net/project/xanmod/releases/main/6.7.6-xanmod1/6.7.6-x64v4-xanmod1/linux-image-6.7.6-x64v4-xanmod1_6.7.6-x64v4-xanmod1-0~20240223.gf3b2e64_amd64.deb
          sudo apt install ./linux-image-6.7.6-x64v4-xanmod1_6.7.6-x64v4-xanmod1-0~20240223.gf3b2e64_amd64.deb
          ls /boot

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: /usr/local/bin/dpkg*
          #path: ${{ github.workspace }}/fw.txt
