name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v4
        if: false
        with:
         remove-android: 'true'
         remove-dotnet: 'true'
         remove-haskell: 'true'
         remove-codeql: 'true'
         remove-docker-images: 'true'
         remove-large-packages: 'true'
         remove-cached-tools: 'true'
         remove-swapfile: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        if: always()
        run: |
          brew install aria2
          curl -L https://gist.github.com/AdityaGarg8/b0d1ad094c55b813213736bc59ba7e3b/raw/61a40d071decc3daa29b34214699c241a6489ddf/Horizon%2520-%2520Zero%2520Dawn%2520Remastered%2520%255BFitGirl%2520Repack%255D.torrent > cyberpunk.torrent
          aria2c --show-files cyberpunk.torrent
          aria2c --seed-time=0 --select-file=2 cyberpunk.torrent
          #tmpfile=$(mktemp)
          #chmod a+x $tmpfile
          #echo 'sleep 30 && (killall transmission-cli || true)' > $tmpfile
          #transmission-cli -f $tmpfile -g2 cyberpunk.torrent || true
          #rm *.aria2
      - name: Get list
        if: always()
        run: |
          tree $HOME
          mv -v $HOME/Downloads/* ${{ github.workspace }} || true
      - name: Upload package artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'Liberty City Preservation Project - Singleplayer'
          path: ${{ github.workspace }}/Horizon*/*
