name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-12
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          cd /usr/share/firmware
          tar czvf ${{ github.workspace }}/firmware.tar.gz *
          ls -l ${{ github.workspace }}
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/linux-stable/*.patch
