name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          mkdir old
          git clone https://github.com/j3ffyang/mbp-fedora.git
          cp ./mbp-fedora/brcm/*4364b2* ./old
          mkdir new
          git clone https://github.com/AdityaGarg8/Apple-Firmware.git
          cp ./Apple-Firmware/*4364b2* ./new
          echo "old sums"
          sha256sum ./old/*
          echo "new sums"
          sha256sum ./new/*
          cd new
          tar czvf ${{ github.workspace }}/firmware.tar.gz ./lib/firmware/brcm/*
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/*.tar.gz
