name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget 'https://libgen.rocks/get.php?md5=e434b6d80b37f5c49ba46cfd01480c9a&key=GZLU4PXSWLUYV6NV'
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/*.pdf
