name: Generate md5 sums
on: [push]
jobs:
  Generate-Sums:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo
      run: |
         git clone https://github.com/t2linux/T2-Ubuntu-Kernel.git
         cd T2-Ubuntu-Kernel
         git checkout --orphan script
         git rm -rf
         echo "Branch of the kernel upgrade script" > README.md
         cd ${{ github.workspace }}
    - name: Push the change
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'Apple-WiFi-Firmware'
        destination-github-username: 'AdityaGarg8'
        destination-repository-name: 'Apple-WiFi-Firmware'
       # user-email: github-actions[bot]@users.noreply.github
    #    user-name: github-actions[bot]
        user-email: gargaditya08@live.com
        user-name: AdityaGarg8
        target-branch: script
        
