name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: macos-latest
    steps:
      - name: Free up disk space for the CI
        if: false
        uses: AdityaGarg8/remove-unwanted-software@v4
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
          verbose: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        shell: cmd
        run: |
          df -h
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          #path: /boot/config*
          path: ${{ github.workspace }}/linux/patches
