name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          curl -#L -O -C - https://github.com/t2linux/T2-Ubuntu/releases/download/v6.9.9-1/kubuntu-24.04-6.9.9-t2-noble.iso.00
          echo retry
          curl -#L -O -C - https://github.com/t2linux/T2-Ubuntu/releases/download/v6.9.9-1/kubuntu-24.04-6.9.9-t2-noble.iso.00
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/firmware.tar.gz
