name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          wget -q https://cdimage.ubuntu.com/ubuntu/releases/23.10/release/ubuntu-23.10-desktop-legacy-amd64.iso
          sudo mount ubuntu-23.10-desktop-legacy-amd64.iso /mnt
          cd /mnt
          tree
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: /mnt/casper/*.manifest
          #path: ${{ github.workspace }}/built-iso.zip
