name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: ubuntu-24.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          #wget -m -np -nH --cut-dirs=3 -e robots=off --reject "index.html*" -P ${{ github.workspace }}/repo https://pkg-repo.blendos.co
          git clone --depth 1 https://github.com/torvalds/linux
          cd linux/drivers/staging
          git clone https://github.com/t2linux/apple-bce-drv.git
          cp -r apple-bce-drv apple-bce
          sudo rm -r apple-bce-drv
          cd apple-bce
          sudo rm -r .git
          sudo rm .gitignore
          sudo rm README.md
          cd ${{ github.workspace }}/linux
          git config --global user.name "FIRST_NAME LAST_NAME"
          git config --global user.email "MY_NAME@example.com"
          git add .
          git commit -m Add apple-bce driver
          git format-patch -1 HEAD
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          #path: /boot/config*
          path: ${{ github.workspace }}/linux/*.patch
