name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Get the kernel upgrade script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: publish
        run: |
         wget https://nightly.link/t2linux/T2-Ubuntu/actions/runs/9766080056/mbp-ubuntu-.z01.zip
         unzip mbp-ubuntu-.z01.zip
