name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget https://github.com/archlinux/linux/archive/refs/tags/v6.10.2-arch1.tar.gz
          wget https://github.com/archlinux/linux/archive/refs/tags/v6.10.3-arch1.tar.gz
          sha256sum ./*.tar.gz
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/tiny-dfr_0.3.1-2_amd64.deb
