name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          git clone --depth=1 -b Ubuntu-6.2.0-27.28 git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/lunar
          git clone --depth=1 https://github.com/mahboobkarimian/t2-paches-for-Ubuntu-kernel patches
          cd lunar
          for patch in ../patches/*.patch; do
          patch -Np1 < $patch
          done
          cp -r ./drivers/net/wireless/broadcom/brcm80211 ${{ github.workspace }}
          cd ${{ github.workspace }}
          zip -r brcm80211.zip brcm80211
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/brcm80211.zip
