name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          sudo apt update
          sudo apt-get install -y build-essential fakeroot libncurses-dev bison flex libssl-dev libelf-dev \
          openssl dkms libudev-dev libpci-dev libiberty-dev autoconf wget xz-utils git \
          libcap-dev bc rsync cpio dh-modaliases debhelper kernel-wedge curl gawk dwarves zstd
          git clone --depth 1 https://git.proxmox.com/git/pve-kernel
          cd pve-kernel
          make
          git format-patch -1 HEAD
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/linux/*.patch
