name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v4
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'
          remove-large-packages: 'false'
          remove-cached-tools: 'false'
          remove-swapfile: 'false'
          verbose: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          #wget -m -np -nH --cut-dirs=3 -e robots=off --reject "index.html*" -P ${{ github.workspace }}/repo https://pkg-repo.blendos.co
          curl -L -O https://github.com/t2linux/T2-Debian-and-Ubuntu-Kernel/releases/download/v6.9.9-1/linux-headers-6.9.9-1-t2-jammy_6.9.9-1_amd64.deb
          curl -L -O https://github.com/t2linux/T2-Debian-and-Ubuntu-Kernel/releases/download/v6.9.9-1/linux-image-6.9.9-1-t2-jammy_6.9.9-1_amd64.deb
          sudo apt install ./*.deb
          sudo apt update
          sudo apt install dkms -y
          git clone -b dfr https://github.com/AdityaGarg8/apple-touchbar-drv.git
          cd apple-touchbar-drv/usr/src/apple-touchbar-advanced-0.1
          make KVERSION=6.9.9-1-t2-jammy
          make clean KVERSION=6.9.9-1-t2-jammy
          cd -
          sudo cp -r apple-touchbar-drv/usr/src/apple-touchbar-advanced-0.1 /usr/src
          sudo dkms install -m apple-touchbar-advanced -v 0.1 -k 6.9.9-1-t2-jammy
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          #path: /boot/config*
          path: ${{ github.workspace }}/linux/patches
