name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: windows-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          pip install -r requirements.txt
          [System.Text.Encoding]::Default
          #python3 main.py
          #pip install pyinstaller
          #pyinstaller --onefile --windowed main.py
          #cd dist
          #.\main.exe
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/ESET-KeyGen/*
