name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: ubuntu-24.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          #wget -m -np -nH --cut-dirs=3 -e robots=off --reject "index.html*" -P ${{ github.workspace }}/repo https://pkg-repo.blendos.co
          DOCKER_IMAGE=debian:12
          docker pull ${DOCKER_IMAGE}
          docker run \
          -t \
          -v "$(pwd)":/repo \
          ${DOCKER_IMAGE} \
          /bin/bash -c 'cd /repo && \
          apt-get update'
          
          DOCKER_IMAGE=debian:unstable
          docker pull ${DOCKER_IMAGE}
          docker run \
          -t \
          -v "$(pwd)":/repo \
          ${DOCKER_IMAGE} \
          /bin/bash -c 'cd /repo && \
          apt-get update'
          
          DOCKER_IMAGE=debian:sid
          docker pull ${DOCKER_IMAGE}
          docker run \
          -t \
          -v "$(pwd)":/repo \
          ${DOCKER_IMAGE} \
          /bin/bash -c 'cd /repo && \
          apt-get update'
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: blendos
          #path: /mnt/casper/*.manifest
          path: ${{ github.workspace }}/linux/*.patch