name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          git clone -b test https://github.com/lemmyg/t2-kubuntu.git
          curl -O https://cdimage.ubuntu.com/kubuntu/releases/24.04.1/release/kubuntu-24.04.1-desktop-amd64.iso
          export ISO_IMAGE=${{ github.workspace }}/kubuntu-24.04.1-desktop-amd64.iso
          cd t2-kubuntu
          bash ./build.sh
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kubuntu
          path: /root/work/output/*.iso
