name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v4
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
          verbose: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          #wget -m -np -nH --cut-dirs=3 -e robots=off --reject "index.html*" -P ${{ github.workspace }}/repo https://pkg-repo.blendos.co
          sudo swapoff -a -v
          sudo rm -f /mnt/swapfile
          #free -h
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          #path: /boot/config*
          path: ${{ github.workspace }}/linux/*.patch
