name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Get the kernel upgrade script
        id: publish
        run: |
          ls -l /usr/share/firmware
          echo
          ls -l /usr/share/firmware/wifi
          echo
