name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh
          chmod +x ubuntu-mainline-kernel.sh
          sudo mv ubuntu-mainline-kernel.sh /usr/local/bin/
          sudo ubuntu-mainline-kernel.sh -i --yes
          ls /boot
