name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --onefile main.py
          chmod a+x ./dist/main
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/ESET-KeyGen/*
