name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          git clone --depth 1 https://github.com/torvalds/linux
          git clone -b aur https://github.com/AdityaGarg8/apple-bce-drv.git
          cp -r ./apple-bce-drv ./linux/drivers/staging/apple-bce
          cd linux
          rm ./drivers/staging/apple-bce/.gitignore
          rm -rf ./drivers/staging/apple-bce/.git
          rm ./drivers/staging/apple-bce/dkms.conf
          rm ./drivers/staging/apple-bce/README.md
          git config --global user.name "Aditya Garg"
          git config --global user.email "gargaditya08@live.com"
          git add .
          git commit -m "Add apple-bce driver"
          git format-patch -1 HEAD
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          #path: /boot/config-6.7.6-x64v4-xanmod1h
          path: ${{ github.workspace }}/linux/0001*.patch
