name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-12
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          brew install coreutils
          curl -L -O https://github.com/AdityaGarg8/Microsoft-ISO-Archive/releases/download/2003/de_office_2003_pro.iso
          sha256sum ./*.iso
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ github.workspace }}/firmware.tar.gz
