name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-12
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          cd $HOME/Downloads
          curl -#L https://github.com/t2linux/T2-Ubuntu/releases/download/v6.3.1-1/kubuntu-23.04-6.3.1-t2-lunar.z01 > kubuntu-23.04-6.3.1-t2-lunar.z01 
          curl -#L https://github.com/t2linux/T2-Ubuntu/releases/download/v6.3.1-1/kubuntu-23.04-6.3.1-t2-lunar.zip > kubuntu-23.04-6.3.1-t2-lunar.zip
          zip -F kubuntu-23.04-6.3.1-t2-lunar.zip --out iso.zip
          unzip iso.zip
          mv $HOME/Downloads/repo/*.iso $HOME/Downloads
          rm -r $HOME/Downloads/repo
          rm $HOME/Downloads/iso.zip
          rm $HOME/Downloads/kubuntu*.z??
          ls -l
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/linux-stable/*.patch
