name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget https://github.com/AdityaGarg8/software-archives/raw/main/EaseUS%20Partition%20Master/EaseUS%20Partition%20Master%2014.5/EaseUS%20Partition%20Master%2014.5.exe
          wget https://github.com/AdityaGarg8/software-archives/raw/main/EaseUS%20Partition%20Master/EaseUS%20Partition%20Master%2014.5/Patcher.exe

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/*.exe
