name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget https://github.com/AdityaGarg8/bnb/releases/download/2024/Neurology.zip
          unzip ./*.zip
          ls

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          #path: /boot/config-6.7.6-x64v4-xanmod1
          path: ${{ github.workspace }}/linux/*.patch
