name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Get the kernel upgrade script
        id: publish
        run: |
         sudo apt update
         sudo apt install -y aria2
