name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          cd ${{ github.workspace }}
          wget -q https://github.com/t2linux/T2-Ubuntu/releases/download/v6.1.14-2/ubuntu-22.10-6.1.14-t2-kinetic.iso
          ISONAME=$(ls ${{ github.workspace }} | grep .iso | rev | cut -d "." -f 1 | rev)
          tar -czvf ${ISONAME}.tar.gz ${{ github.workspace }}/${ISONAME}.iso
          ls -l
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: ${{ github.workspace }}/*.tar.gz
