name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Get the kernel upgrade script
        id: publish
        run: |
          DOCKER_IMAGE=debian:unstable
          docker pull ${DOCKER_IMAGE}
          docker run -t -v "$(pwd):/repo" ${DOCKER_IMAGE} /bin/bash -c 'apt update && apt install curl -y && curl -o /usr/bin/update_t2_kernel "https://raw.githubusercontent.com/t2linux/T2-Ubuntu-Kernel/script/t2-kernel-script/usr/bin/update_t2_kernel" && chmod 755 /usr/bin/update_t2_kernel && update_t2_kernel'
