name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: macos-13
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          #wget -m -np -nH --cut-dirs=3 -e robots=off --reject "index.html*" -P ${{ github.workspace }}/repo https://pkg-repo.blendos.co
          wget https://raw.githubusercontent.com/t2linux/wiki/664a068f7c4f6eba2d6d1f0e0eb9f190fcf1cf90/docs/tools/firmware.sh
          bash ./firmware.sh create_package apt -i
          ls
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          #path: /boot/config*
          path: ${{ github.workspace }}/linux/*.patch
