name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          df -h
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          #path: /boot/config-6.7.6-x64v4-xanmod1h
          path: ${{ github.workspace }}/sketchy.tar.gz
