name: Generate md5 sums
on: [push]
jobs:
  Retrieve-Firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Get kconfig
        run: |
          wget https://github.com/t2linux/T2-Mint/releases/download/v6.8.9-1/linuxmint-21.3-cinnamon-6.8.9-t2-jammy.z01
          wget https://github.com/t2linux/T2-Mint/releases/download/v6.8.9-1/linuxmint-21.3-cinnamon-6.8.9-t2-jammy.zip
          zip -F linuxmint-21.3-cinnamon-6.8.9-t2-jammy.zip --out final.zip
          unzip final.zip
          tree ${{ github.workspace }}
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          #path: /boot/config-6.7.6-x64v4-xanmod1h
          path: ${{ github.workspace }}/firmware
