name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: macos-12
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          wget https://dl.paragon-software.com/demo/ntfsmac15_trial.dmg
          wget https://github.com/AdityaGarg8/software-archives/raw/main/Paragon/NTFS%20for%20Mac.dmg
          md5sum ./*
