---
name: Create tiny-dfr package

on:
  workflow_dispatch:

jobs:
  Publish-Jammy:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 -di | gpg --import
          echo -n "$GPG_SIGNING_KEY" | base64 -di > key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Get the source code
        id: publish
        run: |
          DOCKER_IMAGE=fedora:latest
          docker pull ${DOCKER_IMAGE}
          docker run \
          -e GH_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          -e GPG_SIGNING_EMAIL=${{ secrets.GPG_SIGNING_EMAIL }} \
          -t \
          -v "$(pwd)":/repo \
          ${DOCKER_IMAGE} \
          /bin/bash -c "dnf -y install dnf-plugins-core && dnf -y copr enable sharpenedblade/t2linux && dnf install -y linux-apfs-rw-kmod && (dnf -y copr enable sharpenedblade/t2linux || echo "nooooooo")
