---
name: Create tiny-dfr package

on:
  workflow_dispatch:

jobs:
  Publish-Jammy:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Configure GPG Key
        run: |
          git clone https://github.com/AdityaGarg8/t2-ubuntu-repo.git
          cp -r ./t2-ubuntu-repo/.github/patches ./.github/patches
          cp -r ./t2-ubuntu-repo/.github/scripts ./.github/scripts
          echo -n "$GPG_SIGNING_KEY" | base64 -di | gpg --import
          echo -n "$GPG_SIGNING_KEY" | base64 -di > key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Get the source code
        id: publish
        run: |
          DOCKER_IMAGE=debian:unstable
          docker pull ${DOCKER_IMAGE}
          docker run \
          -e GH_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          -e GPG_SIGNING_EMAIL=${{ secrets.GPG_SIGNING_EMAIL }} \
          -t \
          -v "$(pwd)":/repo \
          ${DOCKER_IMAGE} \
          /bin/bash -c 'apt-get update && \
          DEBIAN_FRONTEND=noninteractive apt-get install -y -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" lsb-release wget && \
          wget https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/bookworm/tiny-dfr_0.2.0-8-bookworm_amd64.deb && \
          apt install ./tiny-dfr_0.2.0-8-bookworm_amd64.deb && \
          lsb_release -c | cut -d ":" -f 2 | xargs && \
          lsb_release -d | cut -d ":" -f 2 | xargs'
